version: "3.3"

networks:
  integration:
    driver: "bridge"

services:
  postgres:
    image: "postgres:9.6.6-alpine"
    hostname: "postgres"
    container_name: postgres
    environment:
      - "POSTGRES_USER=user1"
      - "POSTGRES_PASSWORD=user1"
      - "POSTGRES_DB=db_postgres"
    networks:
      - "integration"
    ports:
      - "54320:5432/tcp"
    restart: always
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 10s
      timeout: 5s
      retries: 5